### ISSUE TITLE
help in C language ..

### ISSUE THREAD

**Issue by r00t-3xp10it** [justin-lathrop/c#19]
hello man can you help me in C ?
i now how to extract **ANCII** chars and **concaternate** them..
what i need to know its how can i **execute** that ancii string after concaternation ..

example:
1º i what to extract the string whoami from ancii chart
2º concaternate the chars to build whoami command
3º and execute the string concaternated ..

this code does allmost everything..
it extracts the chars, concaternate them ...
but it only **prints** the string ..
but i dont what to **print** ..i want to **execute** ..

```
#include <stdio.h>
#include <string.h>

  int main(void)
    {
      /* variable declarations */
      char a = 119;  /* ancii character w */
      char b = 104;  /* ancii character h */
      char c = 111;  /* ancii character o */
      char d = 97;   /* ancii character a */
      char e = 109;  /* ancii character m */
      char f = 105;  /* ancii character i */
 
      /* concaternate and transform decimal values to ancii chars using putchar */
      //char command = putchar('a');putchar('b');putchar('c');putchar('d');putchar('e');putchar('f');

      /* execute command using system() */
      int system(char command);
        system(command);
    }

```

**Comment by ivenpoker** [comment]
The `system` command has prototype as `system(char *command)`. You are passing a character to the `system` function and not a pointer to character (also know as a 'string').

**Comment by r00t-3xp10it** [comment]
objectives of the sourcecode : the **whoami** command must never be written inside the sourcecode
if you look at your example the string **whoami** its there <-- nop its not what i want ..

if i want to simple execute whoami then i will do it this way **system(whoami");** ..

**Comment by bobchris43** [comment]
Hey guys. I need some help. I'm trying to write a c code to partially fill an array of a struct variable. I can't seem to figure out the problem in my code.

Here is the code:

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#define SIZE 10

typedef struct{
	char name[20];
	float score;
}records;

int main()
{
	records n[SIZE];
	records temp;
	int ctr;
	int entries;
	
	printf("Please enter your first name and score\n");
	for(ctr = 0; ctr < SIZE; ctr++)
	{
		scanf("%s %f", &n[ctr].name, &n[ctr].score);
		entries++;
	}
	
	printf("Number of entries: %d", entries);
	
	printf("\nNames            Scores\n");
	for(ctr = 0; ctr < entries; ctr++)
	{
		printf("\n%-15s      %.2f\n", n[ctr].name, n[ctr].score);
	}
}

**Comment by saqlainnaqshi** [comment]
> Hey guys. I need some help. I'm trying to write a c code to partially fill an array of a struct variable. I can't seem to figure out the problem in my code.
> 
> Here is the code:
> 
> #include <stdio.h>
> #include <string.h>
> #include <stdlib.h>
> #define SIZE 10
> 
> typedef struct{
> char name[20];
> float score;
> }records;
> 
> int main()
> {
> records n[SIZE];
> records temp;
> int ctr;
> int entries;
> 
> ```
> printf("Please enter your first name and score\n");
> for(ctr = 0; ctr < SIZE; ctr++)
> {
> 	scanf("%s %f", &n[ctr].name, &n[ctr].score);
> 	entries++;
> }
> 
> printf("Number of entries: %d", entries);
> 
> printf("\nNames            Scores\n");
> for(ctr = 0; ctr < entries; ctr++)
> {
> 	printf("\n%-15s      %.2f\n", n[ctr].name, n[ctr].score);
> }
> ```
> 
> }
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#define SIZE 10

typedef struct{
char name[20];
float score;
}records;

string main()
{
records n[SIZE];
records temp;
int ctr;
int entries;

printf("Please enter your first name and score\n");
for(ctr = 0; ctr < SIZE; ctr++);

scanf("%c %d &n" [ctr].name, &n[ctr].score);
	entries++;


printf("Number of entries: %d", entries);

printf("\nNames            Scores\n");
for(ctr = 0; ctr < entries; ctr++);

printf("\n%-15s      %.2f\n", n[ctr].name, n[ctr].score);
clrscr();
}
