### ISSUE TITLE
help me on the following c code

### ISSUE THREAD

**Issue by friendlm** [justin-lathrop/c#39]
Hi Man

I try to figure out the difference between the "for" and "while", the following code works fine with for loop but it does not work with while loop, what is the problem?

#include <stdio.h>
#define MAXLINE 1000
int getlines(char linestr[], int limitation);
void copy(char to[], char from[]);
main()
{
    int len; /* current line length */
    int max; /* maximum length seen so far */
    char line[MAXLINE]; /* current input line */
    char longest[MAXLINE]; /* longest line saved here */

    max = 0;
    while( (len = getlines(line, MAXLINE)) > 0)
    {
	if(len > max)
	{
	    max = len;
	    copy(longest, line);
	}
    }
    if (max> 0) /* there was a line */
    {
	printf("\n%s", longest);
    }
    return 0;
}
int getlines(char linestr[], int limitation)
{
    int i, c;

    i = 0;
    while((c=getchar()) != EOF && i < limitation - 1)
    {
	if(c == '\n')
	{
	    linestr[i] = c;
	    ++i;
	    linestr[i] = '\0';
	    return i;
	}
	else
	{
	    linestr[i] = c;
	    i++;
	}
    }
}

/*
int getlines(char linestr[], int limitation)
{
    int i;
    int c;
    
    for(i=0; i < limitation - 1 && (c=getchar()) != EOF && c !='\n'; ++i)
    {
	linestr[i] = c;
    }
    if (c == '\n')
    {
	linestr[i] = c;
	++i;
    }
    linestr[i] = '\0';
    return i;
 }
*/

void copy(char to[], char from[])
{
    int i;
    
    for(i=0; (to[i] = from[i]) != '\0'; i++)
	;
}

Best Regards,
Ming

**Comment by DonaldKruse** [comment]
I think the arguments are in the wrong order for `getlines`.

**Comment by viveky1794** [comment]
`
int getlines(char linestr[], int limitation)
{
   int i=0;
  char c;
 
// We get data untill we receive newline charater.
 
while( ( (c=getchar() ) != '\n'  ) && ( i < limitation - 1 ) )
{
    linestr[i++] = c;
}

if(c == '\n')
{
    linestr[i] = c;
    linestr[++i] = '\0';
}
 return i;
}//End
`

**Comment by rohan2301** [comment]
Thank you for your help
