### ISSUE TITLE
C-lang for beginner 

### ISSUE THREAD

**Issue by Hello-Saurabh** [justin-lathrop/c#72]

**Comment by Hello-Saurabh** [comment]
Just basic about C language .

**Comment by Akalya-Coder** [comment]
Hi...
C is a procedural programming language. It was initially developed by **Dennis Ritchie** in the year 1972.
It is Easy to learn

Structured language

It produces efficient programs.

It can handle low-level activities.

It can be compiled on a variety of computers.
All the C programs are writen into text files with extension ".c" for example hello.c. 
A C program basically has the following form:

Preprocessor Commands

Functions

Variables

Statements & Expressions

Comments
